### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by ghost** [alleksandrgall/metaLampServer#1]
1. В проекте достаточно много повторяющихся расширений языка, хорошо бы было их вынести в `package.yaml`
2. Мне кажется это лишним 
https://github.com/alleksandrgall/MynewsServer/blob/93888e8760b1e206697fe6ce98c60451f9b0ad0e/src/Katip/Prod.hs#L66-L67
3. Закомменченные куски кода лучше убрать
https://github.com/alleksandrgall/MynewsServer/blob/93888e8760b1e206697fe6ce98c60451f9b0ad0e/src/Handlers/DB/Scheme.hs#L4-L5
4. Данный тип-сумма создает сразу 3 нетотальные функции, которые могут привести к рантайм ошибке
https://github.com/alleksandrgall/MynewsServer/blob/93888e8760b1e206697fe6ce98c60451f9b0ad0e/src/Api/Article/Get.hs#L96-L97
На мой взгляд, тут проще всего будет поменять тип `nestCChildren` на `Maybe NestCategory`

**Comment by ghost** [comment]
5. Хорошо бы добавить порт, на котором работает сервер, в конфиг

**Comment by alleksandrgall** [comment]
Можешь мне в телеграм написать? У меня есть вопрос по поводу пунка 4
